/*
* This header is generated by classdump-dyld 0.7
* on Thursday, December 17, 2015 at 7:29:44 AM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/CameraUI.framework/CameraUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol CAMExpandableMenuButtonDelegate
@required
-(CGRect*)expandedFrameForMenuButton:(id)arg1;
-(CGRect*)collapsedFrameForMenuButton:(id)arg1;
-(void)collapseMenuButton:(id)arg1 animated:(BOOL)arg2;
-(void)expandMenuButton:(id)arg1 animated:(BOOL)arg2;

@end

