/*
* This header is generated by classdump-dyld 0.7
* on Thursday, December 17, 2015 at 7:29:44 AM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/CameraUI.framework/CameraUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface CAMIOSurfaceWrapper : NSObject {

	void* _surface;

}

@property (nonatomic,readonly) void* surface;              //@synthesize surface=_surface - In the implementation block
-(void)dealloc;
-(id)initWithIOSurface:(void*)arg1 ;
-(void*)surface;
@end

