/*
* This header is generated by classdump-dyld 0.7
* on Thursday, December 17, 2015 at 7:29:48 AM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/CameraUI.framework/CameraUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol CAMNebulaDaemonTimelapseProtocol <CAMNebulaDaemonTimelapseProtocolLimited>
@required
-(void)startTimelapseWithUUID:(id)arg1;
-(void)resumeTimelapseWithUUID:(id)arg1;
-(void)updateTimelapseWithUUID:(id)arg1;
-(void)finishCaptureForTimelapseWithUUID:(id)arg1;
-(void)stopTimelapseWithUUID:(id)arg1;

@end

