/*
* This header is generated by classdump-dyld 0.7
* on Thursday, December 17, 2015 at 7:29:44 AM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/CameraUI.framework/CameraUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <CameraUI/CameraUI-Structs.h>
#import <UIKit/UIView.h>

@class UIView;

@interface CAMPanoramaLevelView : UIView {

	UIView* _lineView;

}

@property (nonatomic,readonly) UIView * lineView;              //@synthesize lineView=_lineView - In the implementation block
-(id)initWithFrame:(CGRect)arg1 ;
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
-(void)layoutSubviews;
-(CGSize)intrinsicContentSize;
-(UIView *)lineView;
@end

