/*
* This header is generated by classdump-dyld 0.7
* on Thursday, December 17, 2015 at 7:29:45 AM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/CameraUI.framework/CameraUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol CAMSuggestionDelegate <NSObject>
@required
-(void)captureController:(id)arg1 didOutputFlashActive:(BOOL)arg2;
-(void)captureController:(id)arg1 didOutputTorchActive:(BOOL)arg2;
-(void)captureController:(id)arg1 didOutputHDRSuggestion:(BOOL)arg2;

@end

